### ISSUE TITLE
Can't draw map with object defined with single coordinate

### ISSUE THREAD

**Issue by anakiK1to** [mipt-npm/maps-kt#20]
When trying to draw a map with only one point/image/etc that has one coordinate,
 it crashes with "DpOffset is unspecified"
When adding a second point/attempting to draw a line/arc/etc that has two coordinates, everything works correctly

**Comment by SPC-code** [comment]
Thank you for reporting. Should be fixed in the next release. Meanwhile a work-around is to provide the ViewPoint manually in Scheme/Map view configuration.
