### ISSUE TITLE
Points feature does not show points in recent release

### ISSUE THREAD

**Issue by ArystanK** [mipt-npm/maps-kt#21]

**Comment by SPC-code** [comment]
Could you please attach an example so we can add it to the demonstration suite?

**Comment by ArystanK** [comment]
@Composable
fun App(component: VisualizationComponent) {
    val state by component.state.collectAsState()

    val viewScope = MapViewScope.remember(state.mapTileProvider)

    MaterialTheme {
        Box(modifier = Modifier.fillMaxSize()) {

            MapView(
                viewScope = viewScope,
                features = FeatureGroup.build(WebMercatorSpace) {
                    state.routesShown.forEach { route ->
                        points(route).color(Color.Blue) // does not show anything
                        
                        // works completely fine
                        var prevPoint: Pair<Double, Double>? = null
                        route.forEach { point ->
                            prevPoint?.let {
                                line(it, point).color(Color.Blue)
                            }
                            prevPoint = point
                        }
                    }

               
                }
            )
           
        }
    }
}

**Comment by SPC-code** [comment]
Confirmed. The problem is that default size for points is `hairline` so they are invisible. The workaround is to defune stroke manually:

```kotlin
            points(
                points = listOf(
                    55.744 to 38.614,
                    55.8 to 38.5,
                    56.0 to 38.5,
                )
            ).modifyAttribute(StrokeAttribute, 5f)
```

If you need polygon, use `multiLine` instead.
